### ISSUE TITLE
Add Option Board Sizes

### ISSUE THREAD

**Issue by jdizzle1988** [asrashley/music-bingo#5]
Hello, this is more of a feature request than an issue. I know Python and have done some development in it. But I can't for the life of me figure out how to get more squares on the bingo board. Is there any way you can add this feature, or assist me in what I need to modify to make this happen? I basically just want to up it to 5x5 squares instead of 5x3.

**Comment by asrashley** [comment]
You could try the [https://github.com/asrashley/music-bingo/tree/refactor] branch, which defines the number of rows and columns in the BingoTicket class (which in musicbingo/generator.py).

**Comment by jdizzle1988** [comment]
Great that is helpful! I will try that out.

**Comment by asrashley** [comment]
Luckily for you I've done the work for you. There are now two new command line options "--rows" and "--columns" which allow you to set the size of each Bingo ticket.
